title: "Cards"
description: |
  Cards can be combined with images and throughout section grids.
patterns:
  main-card:
    title: "Main Card"
    description: |
      These cards are only on the index page. They're cards that display my portfolio pieces, with a hover explination to what the piece is.
    background: "--color-primary"
  mockup-left:
    title: "Mockup Left"
    description: |
      This card was made so that there would be an image on the left (could be a mockup or an image for branding purposes) + text on the right. This card spans the full width of the page, with 2 units side by side.
    background: "--color-secondary"
  mockup-right:
    title: "Mockup Right"
    description: |
      This card was made so that there would be an image on the right (could be a mockup or an image for branding purposes) + text on the left. This card spans the full width of the page, with 2 units side by side.
    background: "--color-primary"
