title: "Banners"
description: |
  Banners can be combined with the header at the top. Currently, there are no buttons that will be going with the banners, as the banners will be handwritten images discussing what will be on the page content.
patterns:
  main-banner:
    title: "Main-Banner"
    description: |
      This will be the standard banner that will always appear at the top of the page. The navigation/header will be ontop of this (transparently).
  banner-header:
    title: "Banner-header"
    description: |
      This banner will be placed ontop of all grids within the website. On the main page, it will be used as a divider called, "Work".

      This will also be used on my Works pages, above the grid displaying the mockups + text content. The name will change and be labeled whatever the artwork is called.
